kind: Service
apiVersion: v1
metadata:
  name: emsprodstat01
  namespace: pucepa
  labels:
    name: emsprodstat01
  annotations:
    description: Exposes an EMS server listen port both inside and outside the cluster.
spec:
  ports:
    - name: tibemsd-port
      protocol: TCP
      port: 30790
      targetPort: 7222
  selector:
    name: emsprodstat01
