apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: cep-application
    deployment: cep-application
    moduleName: cep-slc-has-001
  name: cep-application-cep-slc-has-001
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    app: cep-application
    deployment: cep-application
    moduleName: cep-slc-has-001
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cep-application
        deployment: cep-application
        moduleName: cep-slc-has-001
    spec:
      containers:
        - env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              value: pucepa
            - name: STREAMING_NODENAME
              value: $(MY_POD_NAME).cep-application
            - name: STREAMING_SUBSTITUTIONS
              value: 'fetchSize=10,moduleName="seamlessapplication.cep-slc-has-001",lv-server=lv-server,lv-server-log=lv-server-log,serverURL="jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=OFF)(FAILOVER=ON)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.23.1.15)(PORT=2525)))(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.23.1.16)(PORT=2525)))(CONNECT_DATA=(SERVICE_NAME=PCEPP)))",userName="CEPPAPP",password="ceppapp123!",mongodb-db=pcepp,emsUrl="tcp://emsprod01:30799",emsStatUrl="tcp://emsprodstat01:30790",multiplicity=10,mongodb-db="pcepp"'
          image: >-
            docker-registry.default.svc:5000/pucepa/cep-application-cep-slc-has-001@sha256:b9d86c7b5b3294148e44355818324fbfd899991b02df45795a6bb9cb3fef2341
          imagePullPolicy: Always
          name: cep-application-cep-slc-has-001
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 600
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: '0.5'
              memory: 2Gi
            requests:
              cpu: '0.5'
              memory: 2Gi
          ports:
            - containerPort: 10000
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          stdin: true
          tty: true
      restartPolicy: Always
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - cep-application-cep-slc-has-001
        from:
          kind: ImageStreamTag
          name: 'cep-application-cep-slc-has-001:0.0.1'
      type: ImageChange
