kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: cep-slc-crm-001-autoscalar
  namespace: pucepa
  labels:
    app: cep-application
    deployment: cep-application
    moduleName: cep-slc-crm-001
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: cep-application-cep-slc-crm-001
    apiVersion: apps.openshift.io/v1
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: mem
        targetAverageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75