kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: cep-slc-gcp-002-autoscalar
  namespace: pucepa
  labels:
    app: cep-application
    deployment: cep-application
    moduleName: cep-slc-gcp-002
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: cep-application-cep-slc-gcp-002
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: mem
        targetAverageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75